server:
  servlet:
    context-path: /maquina-velha

spring:
  application:
    name: maquina-velha
  datasource:
    url: jdbc:h2:file:./maquina-velha.db
    username: root
    password: 123
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    path: /doc
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

config:
  tries: 10
  millisWait: 1000