server:
  servlet:
    context-path: /maquina-velha

spring:
  application:
    name: maquina-velha

springdoc:
  swagger-ui:
    path: /doc
  default-consumes-media-type: application/json
  default-produces-media-type: application/json